export const BOOKS = [
    {
        id: 0,
        title: "The Rook",
        author: "M.D. Gardner",
        category: "Adventure",
        image: "https://images.unsplash.com/photo-1550368566-f9cc32d7392d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80",
        featured: true,
        description: "When all else fall in the war on magic, he alone stands tall, thanks to his wits and rings.",
        length: 242,
        release: "10/23/19",
        language "English",
        rating: 4,
    },
    {
        id: 1,
        title: "Black Horizons",
        author: "James Lloyd",
        category: "Adventure",
        image: "https://images.unsplash.com/photo-1472145246862-b24cf25c4a36?ixlib=rb-1.2.1&auto=format&fit=crop&w=1502&q=80",
        featured: false,
        description: "A WW2 pilot flies through a storm cloud and a find a different wold on the other side.",
        length: 213,
        release: "09/29/20",
        language "English",
        rating: 5,
    },
    {
        id: 2,
        title: "Brawler",
        author: "Bo Boxman",
        category: "Adventure",
        image: "https://images.unsplash.com/photo-1552072092-7f9b8d63efcb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80",
        featured: false,
        description: "Cain has been able to punch his way through most his troubles, but the real fight starts now!",
        length: 200,
        release: "01/02/16",
        language "English",
        rating: 3,
    },
    {
        id: 3,
        title: "The Guide to Graphite",
        author: "Jenson Julius",
        category: "Art",
        image: "https://images.unsplash.com/photo-1593435221502-c5d7bfc26cab?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1000&q=80",
        featured: false,
        description: "Almost any form of art starts with a sketch, but sketching is an art form in itself too.",
        length: 109,
        release: "03/06/09",
        language "English",
        rating: 4,
    },
    {
        id: 4,
        title: "Painting 101",
        author: "Dottie Numan",
        category: "Art",
        image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1502&q=80",
        featured: false,
        description: "Covering the basics of painting strokes, color blending, and artistic styles.",
        length: 93,
        release: "06/02/2014",
        language "English",
        rating: 2,
    },
    {
        id: 5,
        title: "Painting 102",
        author: "Dottie Numan",
        category: "Art",
        image: "https://images.unsplash.com/photo-1596567181723-ba7d15eacefb?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=564&q=80",
        featured: false,
        description: "Following up the basics with the differences amongst painting tools and canvases.",
        length: 103,
        release: "08/13/2015",
        language "English",
        rating: 4,
    },
    {
        id: 6,
        title: "The Art of Atomic Bombs",
        author: "Bale Gordon",
        category: "Biography",
        image: "https://images.unsplash.com/photo-1503216963294-431766a5a929?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1500&q=80",
        featured: false,
        description: "Einstein has been called a mad scientist and a genius, but one thing he was was conflicted.",
        length: 349,
        release: "07/21/14",
        language "English",
        rating: 5,
    },
    {
        id: 7,
        title: "Of Balconies and Bullets",
        author: "Dr. Gertrude James",
        category: "Biography",
        image: "https://images.unsplash.com/photo-1562329265-95a6d7a83440?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1328&q=80",
        featured: false,
        description: "President Lincoln is one of the most famous presidents, but what is the story of his killer?",
        length: 250,
        release: "12/10/17",
        language "English",
        rating: 4,
    },
    {
        id: 8,
        title: "Oh Mother!",
        author: "Johnny Lou Mona",
        category: "Biography",
        image: "https://images.unsplash.com/photo-1544652406-55174175da25?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=668&q=80",
        featured: false,
        description: "Behind every man is a mother, but what of Mr. Freud, and his relationship with his parent.",
        length: 163,
        release: "05/30/10",
        language "English",
        rating: 3,
    },
    {
        id: 9,
        title: "By The Numbers",
        author: "Luke Limon",
        category: "Business",
        image: "https://images.unsplash.com/photo-1506555191898-a76bacf004ca?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=668&q=80",
        featured: false,
        description: "An MBA is just a degree. If you want to get a business education, start here!",
        length: 161,
        release: "04/07/10",
        language "English",
        rating: 5,
    },
    {
        id: 10,
        title: "Theory of Nothing",
        author: "Lana Lordes",
        category: "Business",
        image: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1500&q=80",
        featured: false,
        description: "Efficiency at work starts with a clear mind and clean schedule, and the theory of nothing.",
        length: 231,
        release: "12/12/19",
        language "English",
        rating: 4,
    },
    {
        id: 11,
        title: "Lord of Handshakes",
        author: "Jamima Louise",
        category: "Business",
        image: "https://images.unsplash.com/photo-1496115965489-21be7e6e59a0?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=668&q=80",
        featured: false,
        description: "Bargains, agreements, and compromise are the core of any business, so master them.",
        length: 154,
        release: "01/19/18",
        language "English",
        rating: 2,
    },
    {
        id: 12,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 13,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 14,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 15,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 16,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 17,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 18,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 19,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 20,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 21,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 22,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 23,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 24,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 25,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 26,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 27,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 28,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 29,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 30,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 31,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 32,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 33,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 34,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 35,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 36,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 37,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 38,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 39,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 40,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 41,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 42,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 43,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 44,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 45
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 46,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 47,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 48,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 49,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 50,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 51,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 52,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 53,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 54,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 55,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 56,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 57,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 58,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 59,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 60,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 61,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 62,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 63,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 64,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 65,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 66,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 67,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 68,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 69,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 70,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 71,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 72,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 73,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 74,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 75,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: true,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
    {
        id: 76,
        title: "",
        author: "",
        category: "",
        image: "",
        featured: false,
        description: "",
        length: ,
        release: "",
        language "",
        rating: ,
    },
];